/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WaitingRoomImport } from './routes/waiting-room'
import { Route as IndexImport } from './routes/index'
import { Route as PlayerSprintIndexImport } from './routes/player-sprint/index'
import { Route as LoginIndexImport } from './routes/login/index'

// Create/Update Routes

const WaitingRoomRoute = WaitingRoomImport.update({
  id: '/waiting-room',
  path: '/waiting-room',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PlayerSprintIndexRoute = PlayerSprintIndexImport.update({
  id: '/player-sprint/',
  path: '/player-sprint/',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/waiting-room': {
      id: '/waiting-room'
      path: '/waiting-room'
      fullPath: '/waiting-room'
      preLoaderRoute: typeof WaitingRoomImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/player-sprint/': {
      id: '/player-sprint/'
      path: '/player-sprint'
      fullPath: '/player-sprint'
      preLoaderRoute: typeof PlayerSprintIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/waiting-room': typeof WaitingRoomRoute
  '/login': typeof LoginIndexRoute
  '/player-sprint': typeof PlayerSprintIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/waiting-room': typeof WaitingRoomRoute
  '/login': typeof LoginIndexRoute
  '/player-sprint': typeof PlayerSprintIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/waiting-room': typeof WaitingRoomRoute
  '/login/': typeof LoginIndexRoute
  '/player-sprint/': typeof PlayerSprintIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/waiting-room' | '/login' | '/player-sprint'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/waiting-room' | '/login' | '/player-sprint'
  id: '__root__' | '/' | '/waiting-room' | '/login/' | '/player-sprint/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WaitingRoomRoute: typeof WaitingRoomRoute
  LoginIndexRoute: typeof LoginIndexRoute
  PlayerSprintIndexRoute: typeof PlayerSprintIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WaitingRoomRoute: WaitingRoomRoute,
  LoginIndexRoute: LoginIndexRoute,
  PlayerSprintIndexRoute: PlayerSprintIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/waiting-room",
        "/login/",
        "/player-sprint/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/waiting-room": {
      "filePath": "waiting-room.tsx"
    },
    "/login/": {
      "filePath": "login/index.tsx"
    },
    "/player-sprint/": {
      "filePath": "player-sprint/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
