/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as WaitingRoomIndexImport } from './routes/waiting-room/index'
import { Route as SpectatorIndexImport } from './routes/spectator/index'
import { Route as PlayerSprintIndexImport } from './routes/player-sprint/index'
import { Route as LoginIndexImport } from './routes/login/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WaitingRoomIndexRoute = WaitingRoomIndexImport.update({
  id: '/waiting-room/',
  path: '/waiting-room/',
  getParentRoute: () => rootRoute,
} as any)

const SpectatorIndexRoute = SpectatorIndexImport.update({
  id: '/spectator/',
  path: '/spectator/',
  getParentRoute: () => rootRoute,
} as any)

const PlayerSprintIndexRoute = PlayerSprintIndexImport.update({
  id: '/player-sprint/',
  path: '/player-sprint/',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/player-sprint/': {
      id: '/player-sprint/'
      path: '/player-sprint'
      fullPath: '/player-sprint'
      preLoaderRoute: typeof PlayerSprintIndexImport
      parentRoute: typeof rootRoute
    }
    '/spectator/': {
      id: '/spectator/'
      path: '/spectator'
      fullPath: '/spectator'
      preLoaderRoute: typeof SpectatorIndexImport
      parentRoute: typeof rootRoute
    }
    '/waiting-room/': {
      id: '/waiting-room/'
      path: '/waiting-room'
      fullPath: '/waiting-room'
      preLoaderRoute: typeof WaitingRoomIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginIndexRoute
  '/player-sprint': typeof PlayerSprintIndexRoute
  '/spectator': typeof SpectatorIndexRoute
  '/waiting-room': typeof WaitingRoomIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginIndexRoute
  '/player-sprint': typeof PlayerSprintIndexRoute
  '/spectator': typeof SpectatorIndexRoute
  '/waiting-room': typeof WaitingRoomIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/login/': typeof LoginIndexRoute
  '/player-sprint/': typeof PlayerSprintIndexRoute
  '/spectator/': typeof SpectatorIndexRoute
  '/waiting-room/': typeof WaitingRoomIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/player-sprint' | '/spectator' | '/waiting-room'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/player-sprint' | '/spectator' | '/waiting-room'
  id:
    | '__root__'
    | '/'
    | '/login/'
    | '/player-sprint/'
    | '/spectator/'
    | '/waiting-room/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  PlayerSprintIndexRoute: typeof PlayerSprintIndexRoute
  SpectatorIndexRoute: typeof SpectatorIndexRoute
  WaitingRoomIndexRoute: typeof WaitingRoomIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  PlayerSprintIndexRoute: PlayerSprintIndexRoute,
  SpectatorIndexRoute: SpectatorIndexRoute,
  WaitingRoomIndexRoute: WaitingRoomIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/login/",
        "/player-sprint/",
        "/spectator/",
        "/waiting-room/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/login/": {
      "filePath": "login/index.tsx"
    },
    "/player-sprint/": {
      "filePath": "player-sprint/index.tsx"
    },
    "/spectator/": {
      "filePath": "spectator/index.tsx"
    },
    "/waiting-room/": {
      "filePath": "waiting-room/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
